version: "2"
services: 
  gunicorn:
    build:
      context: .
      dockerfile: gunicorn.dockerfile
    ports:
      - 5000:5000
  proxy:
    build: 
      context: .
      dockerfile: haproxy.dockerfile
    ports:
      - 9999:80
